const weapons = [
  "🗡️ Espadão do Cordy (Cordy Greatsword)",
  "🗡️ Espadão do Tevent (Tevent Greatsword)",
  "🛡️ Espada/Escudo Deluznoa (Deluznoa Sword/Shield)",
  "🛡️ Espada/Escudo Belandir (Belandir Sword/Shield)",
  "⚔️ Adaga da Deluznoa (Deluznoa Dagger)",
  "⚔️ Adaga do Tevent (Tevent Dagger)",
  "🎯 Balestra do Cordy (Cordy Crossbow)",
  "🎯 Balestra da Belandir (Belandir Crossbow)",
  "🏹 Arco do Tevent (Tevent Bow)",
  "🏹 Arco da Deluznoa (Deluznoa Bow)",
  "⚡ Cajado da Deluznoa (Deluznoa Staff)",
  "⚡ Cajado da Belandir (Belandir Staff)",
  "🪄 Varinha do Tevent (Tevent Wand)",
  "🪄 Varinha do Cordy (Cordy Wand)",
  "🗡️ Lança da Deluznoa (Deluznoa Spear)",
  "🗡️ Lança da Belandir (Belandir Spear)",
  "🔮 Orb do Tevent (Tevent Orb)",
  "🔮 Orb do Cordy (Cordy Orb)",
  "🥊 Deluzhnoa's Icy Grasp",
  "🥊 Queen Bellandir's Gauntlet",
];

const archbossCodexAliases = [
  {
    localName: "🗡️ Espadão do Tevent (Tevent Greatsword)",
    codexNames: ["Tevent's Warblade of Despair", "Tevent's Warblade of Incineration"],
  },
  {
    localName: "🗡️ Espadão do Cordy (Cordy Greatsword)",
    codexNames: ["Giant Cordy's Ascension Greatsword"],
  },
  {
    localName: "🛡️ Espada/Escudo Deluznoa (Deluznoa Sword/Shield)",
    codexNames: ["Deluzhnoa's Edge of Eternal Frost"],
  },
  {
    localName: "🛡️ Espada/Escudo Belandir (Belandir Sword/Shield)",
    codexNames: ["Queen Bellandir's Languishing Blade"],
  },
  {
    localName: "⚔️ Adaga da Deluznoa (Deluznoa Dagger)",
    codexNames: ["Deluzhnoa's Permafrost Razors"],
  },
  {
    localName: "⚔️ Adaga do Tevent (Tevent Dagger)",
    codexNames: ["Tevent's Fangs of Fury"],
  },
  {
    localName: "🎯 Balestra da Belandir (Belandir Crossbow)",
    codexNames: ["Queen Bellandir's Toxic Spine Throwers"],
  },
  {
    localName: "🎯 Balestra do Cordy (Cordy Crossbow)",
    codexNames: ["Cordy's Stormspore Spike Slingers"],
  },
  {
    localName: "🏹 Arco da Deluznoa (Deluznoa Bow)",
    codexNames: ["Deluzhnoa's Arc of Frozen Death"],
  },
  {
    localName: "🏹 Arco do Tevent (Tevent Bow)",
    codexNames: ["Tevent's Arc of Wailing Death"],
  },
  {
    localName: "⚡ Cajado da Belandir (Belandir Staff)",
    codexNames: ["Queen Bellandir's Hivemind Staff"],
  },
  {
    localName: "⚡ Cajado da Deluznoa (Deluznoa Staff)",
    codexNames: ["Deluzhnoa's Ancient Petrified Staff"],
  },
  {
    localName: "🪄 Varinha do Cordy (Cordy Wand)",
    codexNames: ["Cordy's Grasp of Manipulation"],
  },
  {
    localName: "🪄 Varinha do Tevent (Tevent Wand)",
    codexNames: ["Tevent's Grasp of Withering"],
  },
  {
    localName: "🗡️ Lança da Belandir (Belandir Spear)",
    codexNames: ["Queen Bellandir's Serrated Spike"],
  },
  {
    localName: "🗡️ Lança da Deluznoa (Deluznoa Spear)",
    codexNames: ["Deluzhnoa's Serrated Shard"],
  },
  {
    localName: "🔮 Orb do Cordy (Cordy Orb)",
    codexNames: ["Cordy's Source of Contagion"],
  },
  {
    localName: "🔮 Orb do Tevent (Tevent Orb)",
    codexNames: ["Tevent's Omniscient Eye"],
  },
];

const worldBossWeaponT4Items = [
  "🗡️ Ascended Pakilo Naru's Greatsword",
  "🛡️ Ascended Daigon's Sword",
  "🛡️ Coldblooded Commander Declaration Sword",
  "⚔️ Ascended Leviathan's Daggers",
  "⚔️ Coldblooded Commander Deception Daggers",
  "🎯 Arctic Roar Tracking Crossbows",
  "🎯 Ascended Akman's Crossbows",
  "🏹 Arctic Roar Sniping Bow",
  "🏹 Ascended Leviathan's Bow",
  "⚡ Arctic Roar Staff",
  "⚡ Ascended Daigon's Staff",
  "🪄 Ascended Deckman's Wand",
  "🪄 Coldblooded Wand",
  "🗡️ Ascended Pakilo Naru's Spear",
  "🗡️ Coldblooded Commander Charging Spear",
  "🔮 Arctic Roar Resonating Orb",
  "🔮 Ascended Primal Brothers' Core",
  "🥊 Ahzreil's Flying Strike Gauntlets",
  "🥊 Arctic Roar Charging Gauntlets",
  "🥊 Ascended Leviathan's Gauntlets",
  "🥊 Crimson Valley's Gauntlets of Brutality",
];

const worldBossEquipT4Items = [
  "🎩 Prayer of Salvation Hat",
  "🥋 Blizzard Overture Armor",
  "🥋 Frigid Melody Armor",
  "🧥 North Wind's Tyranny Cloak",
  "🧤 Prophecy of Nine Lives Gloves",
  "🧤 Punisher's Wings Gloves",
  "👢 Azure Sky Apostle Greaves",
  "👢 Hex of Ingenuity Greaves",
  "👢 Stigma Executor Greaves",
];

const worldBossJewelryT4Items = [
  "💎 Ancient Dragon's Claw Earrings",
  "💎 Fallen Goddess' Tears Earrings",
  "📿 Last Dragon's Grudge Necklace",
  "💍 Sacred Tree Resurrection Ring",
  "🔗 Silvermoon Knight Belt",
];

const skillCoreItems = [
  "🧩 A Fúria Negra's Boost (Black Rage's Boost)",
  "🧩 Absorção de Mana (Mana Absorption)",
  "🧩 Acerto Múltiplo (Multi Hit)",
  "🧩 Acúmulo de Acertos (Hit Stack)",
  "🧩 Adaga Hemotóxica (Hemotoxic Dagger)",
  "🧩 Agonia Anunciada (Foretold Agony)",
  "🧩 Anátema do Devoto da Bruxa (Witch Worshipper's Anathema)",
  "🧩 Aniquilação de Barreiras (Barrier Crusher)",
  "🧩 Anjo Acima do Olho da Mente da Fronteira (Angel Above the Frontier's Mind's Eye)",
  "🧩 Armadilha Dupla (Double Trap)",
  "🧩 Armadura do Morto (Dead Man's Armor)",
  "🧩 Armadura Imortal (Immortal Armor)",
  "🧩 Arremesso de Escudo de Pedra (Rock Shield Throw)",
  "🧩 Artimanha (Deception)",
  "🧩 Ataque Espiral (Spiral Assault)",
  "🧩 Avanço Decisivo (Resolute Breakthrough)",
  "🧩 Barragem Concentrada (Focused Barrage)",
  "🧩 Barragem Selvagem (Wild Barrage)",
  "🧩 Barreira de Asa Sombria (Dark Wing's Bulwark)",
  "🧩 Barreira de Devoção (Devotion Barrier)",
  "🧩 Barreira de Força (Strength Barrier)",
  "🧩 Barreira de Pakilo Naru (Pakilo Naru's Barrier)",
  "🧩 Barreira de Pakilo Naru em Fúria (Enraged Pakilo Naru's Barrier)",
  "🧩 Barreira do Escavador (Excavator's Barrier)",
  "🧩 Barreira do Monarca Destrutivo (Destructive Monarch's Barrier)",
  "🧩 Barreira Purgatorial (Purgatorial Barrier)",
  "🧩 Barreira Redentora (Redemptive Barrier)",
  "🧩 Barreira Transcendente de Talus (Talus's Transcendent Barrier)",
  "🧩 Batalha (Battle)",
  "🧩 Bombardeio do Trovão (Thunder Bombardment)",
  "🧩 Canhoto (Southpaw)",
  "🧩 Chamado do Trovão (Thunder Call)",
  "🧩 Choque de Cornélius (Cornelius's Shock)",
  "🧩 Círculo Mágico do Pesadelo (Nightmarish Magic Circle)",
  "🧩 Círculo Mágico Sagrado (Sacred Magic Circle)",
  "🧩 Clamor Purificador (Purifying Cry)",
  "🧩 Clarão (Flash)",
  "🧩 Clarão Azul (Blue Flash)",
  "🧩 Colheita de Almas da Morte Prateada (Silver Reaper's Soul Harvest)",
  "🧩 Comando da Fera Demoníaca Ancestral (Ancient Demonic Beast's Command)",
  "🧩 Condensação de Raios (Lightning Condensation)",
  "🧩 Condutor dos Pesadelos (Nightmare Conductor)",
  "🧩 Constelação Guardiã (Guardian Constellation)",
  "🧩 Contágio (Contagion)",
  "🧩 Corrente Devastadora (Devastating Chain)",
  "🧩 Corte Frenético (Frenzied Slash)",
  "🧩 Crueldade de Pakilo Naru (Pakilo Naru's Cruelty)",
  "🧩 Crueldade de Pakilo Naru em Fúria (Enraged Pakilo Naru's Cruelty)",
  "🧩 Despedaçar (Shatter)",
  "🧩 Despertar do Redemoinho (Whirlpool Awakening)",
  "🧩 Devastação de Deckman (Deckman's Rampage)",
  "🧩 Devastação de Deckman em Fúria (Enraged Deckman's Rampage)",
  "🧩 Disparo de Interrupção (Disruption Shot)",
  "🧩 Disparo Triplo (Triple Snipe)",
  "🧩 Domínio do Caos (Chaos Grasp)",
  "🧩 Eco Carmesim (Crimson Echo)",
  "🧩 Eco do Vazio (Void Echo)",
  "🧩 Ecos de Nébula (Echoes of Nebula)",
  "🧩 Emboscada (Ambush)",
  "🧩 Emboscada do Pecado Miserável (Wretched Sin's Ambush)",
  "🧩 Erosão da Onda de Frio (Cold Snap Erosion)",
  "🧩 Erosão do Medo (Fear Erosion)",
  "🧩 Erupção de Vontade (Will Eruption)",
  "🧩 Escudo Urrante (Roaring Shield)",
  "🧩 Espectro do Leviatã (Leviathan's Specter)",
  "🧩 Espectro do Leviatã Em Fúria (Enraged Leviathan's Specter)",
  "🧩 Espinho Gélido (Icebound Spike)",
  "🧩 Espírito de Chamas de Kowazan (Kowazan's Flame Spirit)",
  "🧩 Estigma Mortal (Mortal Stigma)",
  "🧩 Estrela da Paz (Star of Peace)",
  "🧩 Estrela Purificadora (Purifying Star)",
  "🧩 Estrela Redentora (Redemptive Star)",
  "🧩 Execução (Execution)",
  "🧩 Execução Aniquiladora (Slaughtering Execution)",
  "🧩 Expansão de Círculo Mágico (Magic Circle Expansion)",
  "🧩 Expansão de Geada (Frost Expansion)",
  "🧩 Explosão Crítica (Criticality Explosion)",
  "🧩 Explosão de Nuvens de Trovão (Thunderclouds Explosion)",
  "🧩 Explosão Gélida (Icebound Explosion)",
  "🧩 Feitiço de Reversão (Reversal Spell)",
  "🧩 Feixe Prismático (Prismatic Beam)",
  "🧩 Fixar Alvo (Target Lock)",
  "🧩 Flecha da Ventania (Gale Arrow)",
  "🧩 Flecha de Pedra (Rock Arrow)",
  "🧩 Flecha Explosiva (Explosive Arrow)",
  "🧩 Fogo de Apoio (Support Fire)",
  "🧩 Fome do Rei Lionheart (Lionheart King's Hunger)",
  "🧩 Fragmento de Akman (Akman's Fragment)",
  "🧩 Fragmento de Akman em Fúria (Enraged Akman's Fragment)",
  "🧩 Fratura da Fenda (Rift Fracture)",
  "🧩 Frenesi de Kowazan (Kowazan's Frenzy)",
  "🧩 Frenesi do Campo de Batalha (Battlefield Frenzy)",
  "🧩 Fúria de Adentus (Adentus's Fury)",
  "🧩 Fúria de Aridus (Aridus's Fury)",
  "🧩 Fúria de Daigon (Daigon's Fury)",
  "🧩 Fúria de Daigon Enfurecida (Enraged Daigon's Fury)",
  "🧩 Fúria do Vale do Sangue (Blood Valley Fury)",
  "🧩 Geleira de Talus (Talus's Glacier)",
  "🧩 Golpe da Fera Demoníaca Ancestral (Ancient Demonic Beast's Strike)",
  "🧩 Golpe da Vitória (Victory Strike)",
  "🧩 Golpe de Retaguarda (Rear Strike)",
  "🧩 Golpe Terrestre (Earth Strike)",
  "🧩 Gravação Carmesim (Crimson Imprint)",
  "🧩 Gravação da Dor (Imprint of Pain)",
  "🧩 Gravidade (Gravity)",
  "🧩 Grilhões Urrantes (Roaring Shackles)",
  "🧩 Harmonia Mágica (Magical Harmony)",
  "🧩 Hora do Julgamento (Hour of Judgment)",
  "🧩 Impacto Secundário (Aftershock)",
  "🧩 Ímpeto do Campo de Batalha (Battlefield Momentum)",
  "🧩 Incineração do Leviatã em Fúria (Enraged Leviathan's Incineration)",
  "🧩 Inferno de Junobote (Junobote's Inferno)",
  "🧩 Julgamento (Judgment)",
  "🧩 Julgamento do Rei Sagrado (Sacred King's Judgment)",
  "🧩 Julgamento Veloz (Swift Judgment)",
  "🧩 Lamentação de Minezerok (Minezerok's Lamentation)",
  "🧩 Lâminas de Vento (Wind Blades)",
  "🧩 Lança de Raios (Lightning Spear)",
  "🧩 Lanterna do Herói Corrompido (Corrupt Hero's Lantern)",
  "🧩 Lua Brilhante (Shining Moon)",
  "🧩 Maldição Corrosiva do Devoto da Bruxa (Witch Worshipper's Corrosive Curse)",
  "🧩 Massacre",
  "🧩 Medo Mortal (Scared to Death)",
  "🧩 Melodia de Cura (Healing Melody)",
  "🧩 Melodia dos Pesadelos (Nightmare Melody)",
  "🧩 Morte Rastejante (Creeping Death)",
  "🧩 Movimento Tectônico (Tectonic Shift)",
  "🧩 Muralha de Defesa Mágica de Ahzreil (Ahzreil's Magic Defensive Wall)",
  "🧩 Névoa Abençoada (Blessed Haze)",
  "🧩 Névoa de Gelo (Ice Mist)",
  "🧩 Noite de Trovoadas (Night of Thunderstorms)",
  "🧩 Olho de Ventius (Eye of Ventius)",
  "🧩 Onda (Wave)",
  "🧩 Onda Cortante (Slash Wave)",
  "🧩 Onda de Choque da Ordem Sombria (Dark Order's Shock Wave)",
  "🧩 Onda de Julgamento (Judgment Wave)",
  "🧩 Onda Punitiva (Wave of Punishment)",
  "🧩 Órbita da Estrela (Star's Orbit)",
  "🧩 Ordem de Silêncio da Morte Prateada (Silver Reaper's Gag Order)",
  "🧩 Orientação do Vento (Wind's Guidance)",
  "🧩 Orquestra dos Pesadelos (Nightmare Concerto)",
  "🧩 Ortodoxo (Orthodox)",
  "🧩 Paixão da Bigorna Ensombrada (Black Anvil Passion)",
  "🧩 Pântano Venenoso (Venomous Swamp)",
  "🧩 Pantera Noturna (Night Panther)",
  "🧩 Passos da Fera Demoníaca Ancestral (Ancient Demonic Beast's Footsteps)",
  "🧩 Perseguição Carmesim (Crimson Pursuit)",
  "🧩 Picada do Leviatã (Leviathan's Sting)",
  "🧩 Picada do Leviatã em Fúria (Enraged Leviathan's Sting)",
  "🧩 Poder da Asa Sombria (Dark Wing's Power)",
  "🧩 Ponta de Flecha Furtiva (Stealthy Arrowhead)",
  "🧩 Postura de Assalto (Assault Stance)",
  "🧩 Proteção de Nebula (Nebula's Protection)",
  "🧩 Pulsação de Nébula (Nebula's Pulsation)",
  "🧩 Pulso Mágico de Nirma (Nirma's Magic Pulse)",
  "🧩 Purificação de Clay (Clay's Purification)",
  "🧩 Rajada Gélida (Icebound Gust)",
  "🧩 Recuo (Recoil)",
  "🧩 Ressonância da Nebulosa (Nebula's Resonance)",
  "🧩 Ressonância de Onda (Wave Resonance)",
  "🧩 Retribuição Divina (Divine Retribution)",
  "🧩 Roubo de Bênçãos (Blessing Steal)",
  "🧩 Rugido de Raiva (Roar of Rage)",
  "🧩 Salvação Revigorante (Invigorating Salvation)",
  "🧩 Sede de Kaiser (Kaiser's Thirst)",
  "🧩 Sedução da Guardiã da Flor-espinho (Spineflower Warden's Seduction)",
  "🧩 Semente da Árvore do Mundo (Seed of the World Tree)",
  "🧩 Sentença da Morte Prateada (Silver Reaper's Sentence)",
  "🧩 Sombra do Trovão (Thunder Shadow)",
  "🧩 Sonho do Rei Besta Demônio (Beast King's Dream Demon)",
  "🧩 Sopro de Porfos (Porfos Breath)",
  "🧩 Tempestade de Daigon (Daigon's Storm)",
  "🧩 Tempestade de Daigon Em Fúria (Enraged Daigon's Storm)",
  "🧩 Tempestade de Lâminas (Blade Storm)",
  "🧩 Tempo Falso (False Time)",
  "🧩 Tentação do Devoto da Bruxa (Witch Worshipper's Temptation)",
  "🧩 Terra Calcinada (Scorched Earth)",
  "🧩 Tiro Perfurante (Pierce Shot)",
  "🧩 Tornado Flamejante (Blazing Tornado)",
  "🧩 Torrente (Torrent)",
  "🧩 Tragédia do Ceifeiro de Almas (Soul Reaper's Tragedy)",
  "🧩 Troca de Ataque e Defesa (Attack Defense Swap)",
  "🧩 Trovão de Morokai (Morokai's Thunderbolt)",
  "🧩 Trovão de Ódio e Desilusão (Thunder of Hatred and Disillusionment)",
  "🧩 Trovoada dos Irmãos Primais (Primal Brothers' Thunder Strike)",
  "🧩 Trovoada dos Irmãos Primais em Fúria (Enraged Primal Brothers' Thunder Strike)",
  "🧩 Trovoada Perfurante (Piercing Thunder)",
  "🧩 Túmulo Mortal (Deadly Grave)",
  "🧩 Último Tiro Majestoso (Lofty Last Shot)",
  "🧩 Variação (Variation)",
  "🧩 Vazio de Junobote (Junobote's Void)",
  "🧩 Veneno Ácido (Acidic Poison)",
  "🧩 Veneno Sonífero de Chernobog (Chernobog's Sleep Venom)",
  "🧩 Vento da Imperatriz da Destruição (Destruction Empress's Gale)",
  "🧩 Vento Flamejante de Malakar (Malakar's Blazing Wind)",
  "🧩 Veredito de Thuban (Thuban's Verdict)",
  "🧩 Vigor do Purgatório Ardente (Burning Purgatory's Vigor)",
  "🧩 Vínculo Imortal (Immortal Bond)",
  "🧩 Vitalidade do Grande Aelon (Grand Aelon's Vitality)",
  "🧩 Vontade de Fonsine (Will of Fonsiné)",
  "🧩 Zero Absoluto (Absolute Zero)",
];

const rareItems = [
  "Brooch of Certainty (Broche da Certeza)",
  "Brooch of Nimblesness (Broche da Agilidade)",
  "Brooch of Devastation (Broche da Devastação)",
  "Brooch of Everlasting (Broche da Eternidade)",
  "Brooch of Power Overwhelming (Broche do Poder Avassalador)",
  "Brooch of Awareness (Broche da Consciencia)",
  "Brooch of Primacy (Broche da Primazia)",
  "Necklace of Exceptional Greed (Colar da Avareza Exepctional)",
  "Errant Scion Brim (Pala do Rebento Errante)",
  "Soaring Emblem Ring (Anel do Emblema Ascendente)",
  "Veiled Concord Gloves (Luvas da Concordância Velada)",
  "Umbral Astarch Pants (Calça do Astarca Umbral)",
  "Undying Star Necklace (Colar da Estrela Imortal)",
  "Extinction-proof Periapt (Periapto à Prova de Extinção)",
  "Necklace of Morning Mist (Colar da Névoa da Manhã)",
  "Bracelet of the Evening Tide (Bracelete da Maré Noturna)",
  "Ring of Forbidden Lust (Anel da Luxúria Esquecida)",
  "Coil of Righteous Demand (Espiral da Exigência Virtuosa)",
  "Ring of Divine Retribution (Anel da Retribuição Divina)",
  "Ring of Repeated Death (Anel da Morte Repetida)",
  "Belt of Clutching Fear (Cinto do Medo Angustiante)",
  "Belt of the Dying Spark (Cinto da Centelha Esmorecente)",
  "Ring of Fractal Growth (Anel da Evolução Fractal)",
  "Necklace of Dawn's Light (Colar da Luz da Alvorada)",
  "Blood Crescent Pendant (Pingente da Crescente Sangrenta)",
  "Sash of Rustling Leaves (Faixa das Folhas Farfalhantes)",
  "Crimson Lotus Chestplate (Peitoral do Lotus Carmesim)",
  "Signet of the Alpha (Sinete do alfa)",
  ...worldBossWeaponT4Items,
  ...worldBossEquipT4Items,
  ...worldBossJewelryT4Items,
  ...skillCoreItems,
];

const RARE_ARMOR_ITEMS = new Set([
  "Errant Scion Brim (Pala do Rebento Errante)",
  "Breath of Boundless Sky (Sopro do Céu Sempiterno)",
  "Veiled Concord Gloves (Luvas da Concordância Velada)",
  "Umbral Astarch Pants (Calça do Astarca Umbral)",
  "Crimson Lotus Chestplate (Peitoral do Lotus Carmesim)",
]);

const RARE_ITEM_SET = new Set([
  ...rareItems,
  ...worldBossWeaponT4Items.map(stripLeadingItemEmoji),
  ...worldBossEquipT4Items.map(stripLeadingItemEmoji),
  ...worldBossJewelryT4Items.map(stripLeadingItemEmoji),
  ...skillCoreItems.map(stripLeadingItemEmoji),
]);
const SKILL_CORE_ITEM_SET = new Set([
  ...skillCoreItems,
  ...skillCoreItems.map(stripLeadingItemEmoji),
]);
const WORLD_BOSS_WEAPON_T4_ITEM_SET = new Set([
  ...worldBossWeaponT4Items,
  ...worldBossWeaponT4Items.map(stripLeadingItemEmoji),
]);
const WORLD_BOSS_EQUIP_T4_ITEM_SET = new Set([
  ...worldBossEquipT4Items,
  ...worldBossEquipT4Items.map(stripLeadingItemEmoji),
]);
const WORLD_BOSS_JEWELRY_T4_ITEM_SET = new Set([
  ...worldBossJewelryT4Items,
  ...worldBossJewelryT4Items.map(stripLeadingItemEmoji),
]);

const MAX_RARE_ACCESSORIES_PER_USER = 3;
const MAX_RARE_EQUIPS_PER_USER = 1;
const MAX_SKILL_CORES_PER_USER = 1;
const MAX_WORLD_BOSS_WEAPONS_T4_PER_USER = 1;

function isRareArmor(itemName) {
  return RARE_ARMOR_ITEMS.has(itemName);
}

function isKnownRareItem(itemName) {
  return RARE_ITEM_SET.has(itemName);
}

function isSkillCore(itemName) {
  return SKILL_CORE_ITEM_SET.has(itemName);
}

function isWorldBossWeaponT4(itemName) {
  return WORLD_BOSS_WEAPON_T4_ITEM_SET.has(itemName);
}

function isWorldBossEquipT4(itemName) {
  return WORLD_BOSS_EQUIP_T4_ITEM_SET.has(itemName);
}

function isWorldBossJewelryT4(itemName) {
  return WORLD_BOSS_JEWELRY_T4_ITEM_SET.has(itemName);
}

function stripLeadingItemEmoji(itemName) {
  return String(itemName || "")
    .replace(/^[^\p{L}\p{N}]+/u, "")
    .trim();
}

module.exports = {
  MAX_RARE_ACCESSORIES_PER_USER,
  MAX_RARE_EQUIPS_PER_USER,
  MAX_SKILL_CORES_PER_USER,
  MAX_WORLD_BOSS_WEAPONS_T4_PER_USER,
  isWorldBossEquipT4,
  isWorldBossJewelryT4,
  isRareArmor,
  isKnownRareItem,
  isSkillCore,
  isWorldBossWeaponT4,
  rareItems,
  skillCoreItems,
  stripLeadingItemEmoji,
  archbossCodexAliases,
  worldBossEquipT4Items,
  worldBossJewelryT4Items,
  worldBossWeaponT4Items,
  weapons,
};
